# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a374ff3bebe3afdd42acb142b10cc181edd81e5452f550b5849b3322282f2cd280f8d192e5a2c3048838c2496b1586f81481a8470131bf677030ac35da65fd

test:
  secret_key_base: 611ed77c15e5cafc174d5c8ccabda84938a5cac566f6b0898b60ae315ed7d183dff781aecabe234aa07ebf58f2bfff4a3d075227950c54b54f42a53945418285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
